import { safeSpeechTokens } from './safeSpeechNormalization.js';

export const VOCABULARY_TD_CLUSTER_BEFORE_TO_SOURCE_AUDIT_SHA = '76085365bd3f5759bf3048df427574f350d01191';
export const VOCABULARY_TD_CLUSTER_BEFORE_TO_AUDIT_RECORD_COUNT = 36;

const authorityEntries = [
  {
    id: 'td-cluster-before-to-vocab-00018-proposed-to-propose',
    expected: 'proposed to',
    recognized: 'propose to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00018'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-00069"],
  },
  {
    id: 'td-cluster-before-to-vocab-00485-mind-to-mine',
    expected: 'mind to',
    recognized: 'mine to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00485'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-01883"],
  },
  {
    id: 'td-cluster-before-to-vocab-00499-forced-to-force',
    expected: 'forced to',
    recognized: 'force to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00499'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-01954","wfc-01957"],
  },
  {
    id: 'td-cluster-before-to-vocab-00502-tend-to-ten',
    expected: 'tend to',
    recognized: 'ten to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00502'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-01977","wfc-01978"],
  },
  {
    id: 'td-cluster-before-to-vocab-00561-sentenced-to-sentence',
    expected: 'sentenced to',
    recognized: 'sentence to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00561'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-02183","wfc-02185"],
  },
  {
    id: 'td-cluster-before-to-vocab-00648-used-to-use',
    expected: 'used to',
    recognized: 'use to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00648'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-02515","wfc-02523"],
  },
  {
    id: 'td-cluster-before-to-vocab-00697-engaged-to-engage',
    expected: 'engaged to',
    recognized: 'engage to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00697'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-02718","wfc-02720"],
  },
  {
    id: 'td-cluster-before-to-vocab-01166-apt-to-app',
    expected: 'apt to',
    recognized: 'app to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:01166'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-02939","wfc-02946"],
  },
  {
    id: 'td-cluster-before-to-vocab-01295-failed-to-fail',
    expected: 'failed to',
    recognized: 'fail to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:01295'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-03163"],
  },
  {
    id: 'td-cluster-before-to-vocab-01495-supposed-to-suppose',
    expected: 'supposed to',
    recognized: 'suppose to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:01495'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-03391","wfc-03392"],
  },
  {
    id: 'td-cluster-before-to-vocab-01808-compared-to-compare',
    expected: 'compared to',
    recognized: 'compare to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:01808'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-03849","wfc-03850"],
  },
  {
    id: 'td-cluster-before-to-vocab-01930-determined-to-determine',
    expected: 'determined to',
    recognized: 'determine to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:01930'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-03991","wfc-03992"],
  },
  {
    id: 'td-cluster-before-to-vocab-02046-used-to-use',
    expected: 'used to',
    recognized: 'use to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:02046'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-04076","wfc-04078"],
  },
  {
    id: 'td-cluster-before-to-vocab-02071-refused-to-refuse',
    expected: 'refused to',
    recognized: 'refuse to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:02071'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["wfc-04163"],
  },
  {
    id: 'td-cluster-before-to-vocab-00412-forced-to-force',
    expected: 'forced to',
    recognized: 'force to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00412'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00001"],
  },
  {
    id: 'td-cluster-before-to-vocab-00528-forced-to-force',
    expected: 'forced to',
    recognized: 'force to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00528'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00002"],
  },
  {
    id: 'td-cluster-before-to-vocab-00541-supposed-to-suppose',
    expected: 'supposed to',
    recognized: 'suppose to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00541'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00003"],
  },
  {
    id: 'td-cluster-before-to-vocab-00606-used-to-use',
    expected: 'used to',
    recognized: 'use to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00606'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00005"],
  },
  {
    id: 'td-cluster-before-to-vocab-00628-tend-to-ten',
    expected: 'tend to',
    recognized: 'ten to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00628'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00006"],
  },
  {
    id: 'td-cluster-before-to-vocab-00634-tend-to-ten',
    expected: 'tend to',
    recognized: 'ten to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:00634'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00007"],
  },
  {
    id: 'td-cluster-before-to-vocab-01166-tend-to-ten',
    expected: 'tend to',
    recognized: 'ten to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:01166'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00008"],
  },
  {
    id: 'td-cluster-before-to-vocab-01495-meant-to-men',
    expected: 'meant to',
    recognized: 'men to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:01495'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00009"],
  },
  {
    id: 'td-cluster-before-to-vocab-01810-prepared-to-prepare',
    expected: 'prepared to',
    recognized: 'prepare to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:01810'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00010"],
  },
  {
    id: 'td-cluster-before-to-vocab-01930-mind-to-mine',
    expected: 'mind to',
    recognized: 'mine to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:01930'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00012"],
  },
  {
    id: 'td-cluster-before-to-vocab-02366-prepared-to-prepare',
    expected: 'prepared to',
    recognized: 'prepare to',
    kind: 'connected-speech-td-cluster-before-to',
    credit: 'exact-equivalent',
    scope: { type: 'entry', entryIds: ['vocab:02366'], mode: 'vocabulary' },
    display: 'raw',
    auditCandidateIds: ["tdc-00013"],
  },
];

export const VOCABULARY_TD_CLUSTER_BEFORE_TO_AUTHORITY = Object.freeze(authorityEntries.map(rule => Object.freeze({
  ...rule,
  scope: Object.freeze({ ...rule.scope, entryIds: Object.freeze([...rule.scope.entryIds]) }),
  expectedTokens: Object.freeze(safeSpeechTokens(rule.expected).map(token => token.value)),
  recognizedTokens: Object.freeze(safeSpeechTokens(rule.recognized).map(token => token.value)),
  auditCandidateIds: Object.freeze([...rule.auditCandidateIds]),
})));
